version: '3.8'

services:
  web:
    build:
      context: "./WEB NEW"
      dockerfile: Dockerfile.dev
      args:
        VITE_API_BASE_URL: http://localhost:3000/api
        VITE_APP_API_IMAGE: http://localhost:3000/
        VITE_APP_PDF_LICENSE: demo:1734577804655:7ea8e4310300000000c8233fd7af5b03b95ca487e4adb98e8228071952
    ports:
      - "5173:5173"
    volumes:
      - ./WEB NEW/src:/app/src
      - ./WEB NEW/public:/app/public
      - /app/node_modules
    environment:
      - NODE_ENV=development

  api:
    build:
      context: ./API
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./API:/usr/src/app
      - /app/node_modules
      - ./API/uploads:/usr/src/app/uploads
      - ./API/logs:/usr/src/app/logs    
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your-secret-key-here
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my-strong-password
      - DB_NAME=railway
      - JWT_SECRET=your_jwt_secret
      - DB_PORT=3306

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-strong-password
    volumes:
      - db_data:/var/lib/mysql 
volumes:
  db_data: