[build]
builder = "nixpacks"

[deploy]
# healthcheckPath = "/api"
# healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "api"
source = "API"
[services.build]
builder = "nixpacks"
[services.deploy]
startCommand = "npm start"
# healthcheckPath = "/api"
# healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
source = "WEB NEW"
[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
[services.deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
