# nginx.conf

server {
    listen 80;
    server_name localhost;

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    types {
        application/javascript mjs;
        application/wasm wasm;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Additional configurations go here...
}
