/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<
      'root',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '$error': RouteRecordInfo<
      '$error',
      '/:error(.*)',
      { error: ParamValue<true> },
      { error: ParamValue<false> },
      | never
    >,
    '403': RouteRecordInfo<
      '403',
      '/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-classes-all': RouteRecordInfo<
      'admin-classes-all',
      '/admin/classes/all',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-classes-attendance': RouteRecordInfo<
      'admin-classes-attendance',
      '/admin/classes/attendance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-classes-calendar': RouteRecordInfo<
      'admin-classes-calendar',
      '/admin/classes/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-classes-copy-id': RouteRecordInfo<
      'admin-classes-copy-id',
      '/admin/classes/copy/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin-classes-create': RouteRecordInfo<
      'admin-classes-create',
      '/admin/classes/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-classes-edit-id': RouteRecordInfo<
      'admin-classes-edit-id',
      '/admin/classes/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin-classes-view-id': RouteRecordInfo<
      'admin-classes-view-id',
      '/admin/classes/view/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin-dashboard': RouteRecordInfo<
      'admin-dashboard',
      '/admin/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-library': RouteRecordInfo<
      'admin-library',
      '/admin/library',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-logs': RouteRecordInfo<
      'admin-logs',
      '/admin/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-materials-all': RouteRecordInfo<
      'admin-materials-all',
      '/admin/materials/all',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-materials-create': RouteRecordInfo<
      'admin-materials-create',
      '/admin/materials/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-materials-edit-id': RouteRecordInfo<
      'admin-materials-edit-id',
      '/admin/materials/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin-setting': RouteRecordInfo<
      'admin-setting',
      '/admin/setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-student-all': RouteRecordInfo<
      'admin-student-all',
      '/admin/student/all',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-student-create': RouteRecordInfo<
      'admin-student-create',
      '/admin/student/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-student-edit-id': RouteRecordInfo<
      'admin-student-edit-id',
      '/admin/student/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin-student-materials': RouteRecordInfo<
      'admin-student-materials',
      '/admin/student/materials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-student-view-id': RouteRecordInfo<
      'admin-student-view-id',
      '/admin/student/view/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin-teacher-all': RouteRecordInfo<
      'admin-teacher-all',
      '/admin/teacher/all',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-teacher-create': RouteRecordInfo<
      'admin-teacher-create',
      '/admin/teacher/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-teacher-edit-id': RouteRecordInfo<
      'admin-teacher-edit-id',
      '/admin/teacher/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin-teacher-materials': RouteRecordInfo<
      'admin-teacher-materials',
      '/admin/teacher/materials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-teacher-view-id': RouteRecordInfo<
      'admin-teacher-view-id',
      '/admin/teacher/view/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin-users': RouteRecordInfo<
      'admin-users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-users-create': RouteRecordInfo<
      'admin-users-create',
      '/admin/users/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin-users-edit-id': RouteRecordInfo<
      'admin-users-edit-id',
      '/admin/users/edit/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'student-class': RouteRecordInfo<
      'student-class',
      '/student/class',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'student-library': RouteRecordInfo<
      'student-library',
      '/student/library',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'student-materials': RouteRecordInfo<
      'student-materials',
      '/student/materials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'teacher-class': RouteRecordInfo<
      'teacher-class',
      '/teacher/class',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'teacher-materials': RouteRecordInfo<
      'teacher-materials',
      '/teacher/materials',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'root'
      views:
        | never
    }
    'src/pages/[...error].vue': {
      routes:
        | '$error'
      views:
        | never
    }
    'src/pages/403.vue': {
      routes:
        | '403'
      views:
        | never
    }
    'src/pages/admin/classes/all.vue': {
      routes:
        | 'admin-classes-all'
      views:
        | never
    }
    'src/pages/admin/classes/attendance.vue': {
      routes:
        | 'admin-classes-attendance'
      views:
        | never
    }
    'src/pages/admin/classes/calendar.vue': {
      routes:
        | 'admin-classes-calendar'
      views:
        | never
    }
    'src/pages/admin/classes/copy/[id].vue': {
      routes:
        | 'admin-classes-copy-id'
      views:
        | never
    }
    'src/pages/admin/classes/create.vue': {
      routes:
        | 'admin-classes-create'
      views:
        | never
    }
    'src/pages/admin/classes/edit/[id].vue': {
      routes:
        | 'admin-classes-edit-id'
      views:
        | never
    }
    'src/pages/admin/classes/view/[id].vue': {
      routes:
        | 'admin-classes-view-id'
      views:
        | never
    }
    'src/pages/admin/dashboard.vue': {
      routes:
        | 'admin-dashboard'
      views:
        | never
    }
    'src/pages/admin/library.vue': {
      routes:
        | 'admin-library'
      views:
        | never
    }
    'src/pages/admin/logs.vue': {
      routes:
        | 'admin-logs'
      views:
        | never
    }
    'src/pages/admin/materials/all.vue': {
      routes:
        | 'admin-materials-all'
      views:
        | never
    }
    'src/pages/admin/materials/create.vue': {
      routes:
        | 'admin-materials-create'
      views:
        | never
    }
    'src/pages/admin/materials/edit/[id].vue': {
      routes:
        | 'admin-materials-edit-id'
      views:
        | never
    }
    'src/pages/admin/setting.vue': {
      routes:
        | 'admin-setting'
      views:
        | never
    }
    'src/pages/admin/student/all.vue': {
      routes:
        | 'admin-student-all'
      views:
        | never
    }
    'src/pages/admin/student/create.vue': {
      routes:
        | 'admin-student-create'
      views:
        | never
    }
    'src/pages/admin/student/edit/[id].vue': {
      routes:
        | 'admin-student-edit-id'
      views:
        | never
    }
    'src/pages/admin/student/materials.vue': {
      routes:
        | 'admin-student-materials'
      views:
        | never
    }
    'src/pages/admin/student/view/[id].vue': {
      routes:
        | 'admin-student-view-id'
      views:
        | never
    }
    'src/pages/admin/teacher/all.vue': {
      routes:
        | 'admin-teacher-all'
      views:
        | never
    }
    'src/pages/admin/teacher/create.vue': {
      routes:
        | 'admin-teacher-create'
      views:
        | never
    }
    'src/pages/admin/teacher/edit/[id].vue': {
      routes:
        | 'admin-teacher-edit-id'
      views:
        | never
    }
    'src/pages/admin/teacher/materials.vue': {
      routes:
        | 'admin-teacher-materials'
      views:
        | never
    }
    'src/pages/admin/teacher/view/[id].vue': {
      routes:
        | 'admin-teacher-view-id'
      views:
        | never
    }
    'src/pages/admin/users/index.vue': {
      routes:
        | 'admin-users'
      views:
        | never
    }
    'src/pages/admin/users/create.vue': {
      routes:
        | 'admin-users-create'
      views:
        | never
    }
    'src/pages/admin/users/edit/[id].vue': {
      routes:
        | 'admin-users-edit-id'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/pages/student/class.vue': {
      routes:
        | 'student-class'
      views:
        | never
    }
    'src/pages/student/library.vue': {
      routes:
        | 'student-library'
      views:
        | never
    }
    'src/pages/student/materials.vue': {
      routes:
        | 'student-materials'
      views:
        | never
    }
    'src/pages/teacher/class.vue': {
      routes:
        | 'teacher-class'
      views:
        | never
    }
    'src/pages/teacher/materials.vue': {
      routes:
        | 'teacher-materials'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
