services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3010:3000"
    depends_on:
      - db
    # volumes:
      # - ./:/app
      # - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your-secret-key-here
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my-strong-password
      - DB_NAME=railway
      - JWT_SECRET=your_jwt_secret
      - DB_PORT=3306
    restart: always
    develop:
      watch:
        - action: sync
          path: ./
          target: /app/
          ignore:
            - node_modules/

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-strong-password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql